### ISSUE TITLE
Automate Data Pages

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#111]
Currently the data pages live in a folder hard-coded to a business. The data a business lives in a tab of a google spreadsheet.
- [x] Create a generic page for a business.
- [x] Remove hard-coded business names.

Out of scope:
- Customized "Overall Wellness" png. It will hard code existing diamond pngs only.

**Comment by ezbycer** [comment]
@boonrs On the coding of diamond pngs, does that mean it will also do new ones moving forward?

**Comment by boonrs** [comment]
If the naming convention for them holds constant, then it will handle the pngs. The naming convention assumes that the png is named the same as the google sheet for the  business plus "-diamond.png". For example, the google sheet is named "cabq-hr" and the png is named "cabq-hr-diamond.png".

**Comment by ezbycer** [comment]
@williamtyner @jenningshanna Pull request #113 will close this issue. See the line above from @boonrs about the naming convention, and please make sure that is included in documentation.
