### ISSUE TITLE
Add a way to quickly get to all pages.

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#24]
Currently, there isn't a way to navigate to the manage page. Since this is a prototype, we should add a way for people to quickly get to the three pages.

A simple way to do this might be adding links to the footer. Choose your own adventure. Feel free to come talk to me if additional guidance is needed.

**Comment by williamtyner** [comment]
@boonrs Two simple nav bars for all components of the site. 

![img_4924_1](https://cloud.githubusercontent.com/assets/10442125/9017487/b62823a4-378b-11e5-9dd0-604ed3ed56ac.jpg)

![img_4924_2](https://cloud.githubusercontent.com/assets/10442125/9017488/b80075dc-378b-11e5-9400-ae67f9a670b2.jpg)

**Comment by jenningshanna** [comment]
@williamtyner should I knock this out?
