### ISSUE TITLE
Order results by something

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#3]
We need to order the directory results for the user based on what they choose in the wizard.

To accomplish that, we need to rectify the difference in the wizard scale and the mock data scale.

In the [wizard](http://codeforamerica.github.io/abq-financial-wellness-wizard/), the user can rank their stress on the following scale:
- not stressed
- stressed
- very stressed
- hopeless

The [data](https://docs.google.com/spreadsheets/d/1hcZfADUtL0NKFJoY3TSSuYIbUy9W4xTT22fu1uHX52I/edit#gid=0) has the following scale:
- I have some time
- Soon
- Now

**Comment by williamtyner** [comment]
I will take care of this. I think it's best to use the wizard scale.

**Comment by boonrs** [comment]
ok, no need to remove the data's time ranking. just and a column for stress.

**Comment by jenningshanna** [comment]
That data is for time not stress level. It would coordinate 1 = "now", 2 =  "Soon", 3 = "I have some time", there is no col for stress level now as in the old format it wasn't something we had planned on capturing.

**Comment by boonrs** [comment]
I will sort by stress level, which @williamtyner has kindly added to the data.
