### ISSUE TITLE
Add some color

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#32]
Add some color to
- [x] Header
- [x] Charts
- [x] Footer
- [x] Button hover
- [x] Directory table bg
- [x] Links

**Comment by boonrs** [comment]
To update chart colors, update the array of hex values at the top of the manage.js file.

**Comment by jenningshanna** [comment]
oh thanks @boonrs, I thought there was an issue for this but I totally missed it :whale: 

also, how do you make those checkboxes in MD?

**Comment by jenningshanna** [comment]
theme: https://color.adobe.com/Sandias-color-theme-6625850/

(based off Sandia mtns colors as the sun sets)
