### ISSUE TITLE
savings/billings chart style

### ISSUE THREAD

**Issue by jenningshanna** [codeforamerica/abq-financial-wellness-wizard#41]
![screen shot 2015-08-03 at 10 59 09 am](https://cloud.githubusercontent.com/assets/2494205/9044048/bce82104-39ce-11e5-9f1e-3ef6220df348.png)

@boonrs make the chart a billion times better by showing the count on the vertical bar line :moneybag: :moneybag: :moneybag:

**Comment by boonrs** [comment]
lolol :godmode:
