### ISSUE TITLE
Turn pie into donuts

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#46]
Donuts are tastier :cake:

**Comment by jenningshanna** [comment]
Although we unanimously agree that Donuts > Pie this issue is no longer relevant as the new report will have it's own brand new tasty elements for which we can judge soon. Closing.

**Comment by ErnieAtLYD** [comment]
Just came here to remark that I've always thought doughnuts were better than pie.
