### ISSUE TITLE
Create Forms for User Review based on CFPB Matrix

### ISSUE THREAD

**Issue by jenningshanna** [codeforamerica/abq-financial-wellness-wizard#55]
@boonrs, here are the questions to be added to the evaluation tool that I'll start getting user feedback on soon. Please let us know if you have questions or concerns. Thanks! 

The Matrix is from _Present to Future : Security to Freedom_.

![financial_wellness_matrix](https://cloud.githubusercontent.com/assets/2494205/9319534/636e2ae2-4504-11e5-9156-25e256228838.png)
### Overview Questions
1. How often do you feel stress over finances?
   - Every day
   - Weekly
   - Monthly
   - Not often
2. If you had to choose one, which one of the options below would you say causes the most stress?
   - Paying Bills
   - Saving Money
   - Freedom to Spend Money
   - Setting Goals
##### Feeling in control and confident about your money
1. How much of your monthly income goes towards bills?
   - Some
   - Most
   - All
   - Not Sure
2. How often do you worry about covering all of your expenses in a month?
   - Never
   - Sometimes
   - Often
   - Not Sure
3. Do you ever miss a bill payment?
   - Never
   - Sometimes
   - Often
   - Not Sure
##### Absorbing financial bumps when they happen
1. How often do you put money into savings?
   - Never
   - Sometimes
   - Often
   - Not Sure
2. How often do you take money out of savings to cover an expense?
   - Never
   - Sometimes
   - Often
   - Not Sure
3. If you could go without working, how long would you savings support you?
   - One Month or Less
   - Two to Three Months
   - Six Months or More
   - Not Sure
##### Having the flexibility to spend money
- How often do you feel like you have the financial freedom to do the following?
  - Be generous with family or friends?
    - Never, Sometimes, Often, Not Sure
  - Continuing to develop professionally through education or job training?
    - Never, Sometimes, Often, Not Sure
  - Taking a vacation?
    - Never, Sometimes, Often, Not Sure
##### Getting on track to meet financial goals
- In the future, how much would you prioritize?
  - Be generous with family or friends?
    - Never, Sometimes, Often, Not Sure
  - Continuing to develop professionally through education or job training?
    - Never, Sometimes, Often, Not Sure
  - Taking a vacation?
    - Never, Sometimes, Often, Not Sure
##### Is there anything we didn't cover that you'd like for us to know?

**\* INPUT BOX ***

**Comment by williamtyner** [comment]
@boonrs @jenningshanna

**Comment by boonrs** [comment]
@williamtyner @jenningshanna 
Based on these inputs, what outputs are expected? In our prototype, the main emphasis is filtering a list of services for a user based on their selection of "Paying Bills" or "Saving Money". 

Could you identify the purpose of each question? For example, if a question applies specifically to a [taxonomy](http://socialservicedata.org/taxonomy/tags/) for a service (aids in filtering services) and how it weighs in the financial wellness metric.

**Comment by jenningshanna** [comment]
For now it is simply collecting response data. Working with servicing partners to understand what and how (that's who I was talking to this morning). Also wanted them to help us build the taxonomy.

**Comment by boonrs** [comment]
Let servicing partners know they don't have to build the taxonomy from scratch. Point them towards existing ones for this space.

**Comment by jenningshanna** [comment]
:shipit:
