### ISSUE TITLE
Make the wizard friendlier.

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#6]
Use text from  [this document](https://docs.google.com/document/d/1VgUsdroV0-0N8AIDzR4dh5E6HsGRQYYG5-h1L3Bc90Y/edit#).
- [x] Add intro text.
- [x] Add quotations to appropriate wizard steps.

**Comment by jenningshanna** [comment]
I've been looking at this and don't really understand how to add this text dynamically :(

**Comment by boonrs** [comment]
@jenningshanna let's take a look at this together when you have a minute. you know where to find me!

**Comment by boonrs** [comment]
Was intro text added? I'm missing where it was added.

**Comment by jenningshanna** [comment]
good catch :baseball:

**Comment by jenningshanna** [comment]
sooo.. when I merge the branch does it close this issue, @boonrs?
