### ISSUE TITLE
Auto Scroll with questions

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#60]
It's annoying to have to scroll down after you answer a question.

**Comment by jenningshanna** [comment]
YES! This was going to be my next ask! :+1: 

My only concern is mobile and tablet responses to this. Are you concerned about that?

**Comment by boonrs** [comment]
Not at this point. We  have a way to go moving this from prototype to mvp. As we still don't have clear direction, time spent on bells and whistles needs to be on the smaller size.
