### ISSUE TITLE
Exit survey on the thank you page

### ISSUE THREAD

**Issue by jenningshanna** [codeforamerica/abq-financial-wellness-wizard#66]
As Efrem expressed we need to get more feedback on what the individual employee wants as far as resources and services displayed when they have completed the report:
- [x] define questions through UserTesting.com feedback
- [x] outline ?s (multiple choice)
- [x] create in Wufoo for easy capturing
- [x] embed Wufoo form in thank you page

**Comment by boonrs** [comment]
I'm not sure I understand this. We're asking people to create a second form after filling out ours?

**Comment by williamtyner** [comment]
@jenningshanna I agree with @boonrs. My assumption is that it would disrupt the experience to have the user go to another survey on another site. 

## Exit Survey Questions

**1. If you could have your own financial well-being report, what would you want it to include?**

Rental Assistance
Tax Credits
Small Dollar Loans
Savings Accounts
Financial Literacy Classes & Workshops
Financial Coaching

**2. What are the things you would want your employer to see in a report like this? and why? (remember it’s anonymous)**

Open-ended

**Comment by jenningshanna** [comment]
1. @williamtyner @boonrs is not saying that nor are we. The survey will be embedded in our thank you page.
2. @boonrs this came out of a discussion with Efrem this morning and we can easily catch you up

**Comment by jenningshanna** [comment]
@williamtyner I was thinking of this more as a list of "could be useful" choices like: rental assistance, tax credits, small loans, savings accounts, financial lit classes, capacity tools, tools like mint, and so on. In which the survey'ee could respond in the moment.

Also, I don't necessarily think we should ask them about what they liked MOST as I did in the user test. The reason being that in a PILOT things are meant to seam real, not half-real. And asking this user for product feedback is probably counter-intuitive to our output.

**Comment by williamtyner** [comment]
updated! @jenningshanna

**Comment by jenningshanna** [comment]
@williamtyner Here's what I made the form up of that's now live on the MRCOG thank you page. Again, we don't want to merge data that's being collected from separate pilots. Closing this task for now.
![screen shot 2015-09-01 at 12 46 30 pm](https://cloud.githubusercontent.com/assets/2494205/9614839/15471440-50a9-11e5-8efd-8c43a36b3c2c.png)

**Comment by williamtyner** [comment]
great selections. Nice job.
