### ISSUE TITLE
Bar and Pie Charts for Pilot Reports

### ISSUE THREAD

**Issue by jenningshanna** [codeforamerica/abq-financial-wellness-wizard#86]
Create bar and pie charts from this data:
https://docs.google.com/spreadsheets/d/106PF88IzRnMGG1nbqYYjSqURft8v0fOjb9AFHvdYNic/edit#gid=2082954293

Bar charts will cover the two overview questions and a pie chart for each of the rest of the columns. I can duplicate the charts and create the individual reports if you simpley make the two and provide some instruction as to how to change the column and sheet.

Here are examples of each:
![screen shot 2015-09-17 at 10 49 35 am](https://cloud.githubusercontent.com/assets/2494205/9941383/d0fdebaa-5d29-11e5-86db-9af26311ebb5.png)

**Comment by boonrs** [comment]
Closed by #89
