### ISSUE TITLE
Display answers to the "Open Forum" question.

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#94]
- [x] Users should see the answers one at a time.
- [x] Display in a carousel.

**Estimate:** 8 hours

**Comment by boonrs** [comment]
@ezbycer Is it correct to say we only show the answers to these questions on the business specific pages? We do not show them on the accumulative data page.

**Comment by ezbycer** [comment]
@boonrs I think it makes sense for the answers to go on both
