### ISSUE TITLE
Add a page to display resources.

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#95]
- [x] Display in a table
- [x] Add a way to filter by CFPB tag.

**Estimate:** 8 hours

**Comment by ezbycer** [comment]
Does this mean toggles as well? @boonrs

**Comment by boonrs** [comment]
@ezbycer Filter = "toggles" That's the essence of the functionality being asked for. A way to filter the data by CFPB tag.

**Comment by ezbycer** [comment]
Awesome. Sounds good. I'm getting brought up to speed on the terminology
myself. Thanks!

On Fri, Oct 9, 2015 at 12:28 PM, Becky Boone notifications@github.com
wrote:

> @ezbycer https://github.com/ezbycer Filter = "toggles" That's the
> essence of the functionality being asked for. A way to filter the data by
> CFPB tag.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/abq-financial-wellness-wizard/issues/95#issuecomment-146978939
> .

## 

Efrem Z. Bycer | Director of Economic Development | Code for America
http://www.codeforamerica.org/ | C: 802-578-7997 | @ezbycer
