### ISSUE TITLE
Tag Resources data

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#97]
In order to filter by the CFPB matrix tags, the resource data needs to have the tags associated with the data. Please add the following tags to the data:
- present-security
- present-freedom
- future-security
- future-freedom

The resource data is located [here](https://docs.google.com/spreadsheets/d/1hcZfADUtL0NKFJoY3TSSuYIbUy9W4xTT22fu1uHX52I/edit#gid=0)

**Comment by williamtyner** [comment]
closes #97
