### ISSUE TITLE
Standardize resource urls

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#98]
Standardize url for resources.
- [ ] Add http or https in front of all urls.

The source data for resources is [here](https://docs.google.com/spreadsheets/d/1hcZfADUtL0NKFJoY3TSSuYIbUy9W4xTT22fu1uHX52I/edit#gid=0).

Currently, the url for resources is not standardized. They either have http in front, or don't. This causes some links to not work when listed in a table. Example:
- https://docs.google.com/spreadsheets/d/1hcZfADUtL0NKFJoY3TSSuYIbUy9W4xTT22fu1uHX52I/edit#gid=0
- cabq.gov/family/facilities-centers/health-social-services-centers

**Comment by williamtyner** [comment]
Hey Becky,

FYI we are using the following template with all of the tags and CFPB categorization. 

https://docs.google.com/spreadsheets/d/1sTasDpO_Ay2YLFLFGgrIOQ9KYzB5SK3DU5mKBmcK6sE/edit#gid=1856021763

**Comment by williamtyner** [comment]
closes #98

**Comment by boonrs** [comment]
Thanks for clarifying @williamtyner. 

That's a different url than was in the [template provided](https://github.com/codeforamerica/abq-financial-wellness-wizard/blob/gh-pages/manage/resources.html).
