### ISSUE TITLE
Unused Links

### ISSUE THREAD

**Issue by boonrs** [codeforamerica/abq-financial-wellness-wizard#99]
Are the following pages being used:
- http://codeforamerica.github.io/abq-financial-wellness-wizard/CABQ-HR/
- http://codeforamerica.github.io/abq-financial-wellness-wizard/HeadingHome/
- http://codeforamerica.github.io/abq-financial-wellness-wizard/MRCOG/

If so, they need to be updated with the latest styles. If not, they can be deleted.

**Comment by jenningshanna** [comment]
Keep these as they'll be reused in a re-evaluation to a certain extent.
